[package]
name = "rustysm"
version = "0.1.0"
authors = ["medlem <medlem@ink>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.14"
alsa = "0.4.3"
termion = "1.5"
notify = "4.0.12"
easy_reader = "0.5.0"